---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          # image: flask-docker-demo-app
          # imagePullPolicy: Never
          image: 373669830907.dkr.ecr.us-east-1.amazonaws.com/flask-docker-demo-app:latest
          imagePullPolicy: Always
          ports:
            # - containerPort: 5000
            - containerPort: 80