---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  externalTrafficPolicy: Local
  ports:
  # - port: 5000
  #   protocol: TCP
  #   targetPort: 5000
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flaskapi
  type: LoadBalancer